# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63a049e3ceb4a5047c0229e33be76e9328bf00f3b0bbace1eb3f1a034e8a8abe3dde710ffd26d5674f8fe98d5dafcee7d99aac4c81605c2f322f1e82f2ed149b

test:
  secret_key_base: 6074a784c11e60614c77b8fe49f5d6b8812369ccb487b81d24d7ecb0c4e08827e099b74673292456ac2e3f632422b2006e949f866f7f7c1eaaf108f7f78380a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
